services:
  db:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s
  web:
    build: .
    command: sh -c "python3 manage.py migrate && gunicorn scentinel.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - static:/app/static
      - media:/app/media
      - ./.env:/app/.env
    depends_on:
      db:
        condition: service_healthy
        restart: true
  nginx:
    build: ./nginx
    volumes:
      - static:/app/static/
      - media:/app/media/
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  db-data:
  media:
  static:
