# Generated by Django 5.1.5 on 2025-03-06 13:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import scents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loc_gps",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="GPS location"
                    ),
                ),
                ("loc_desc", models.TextField(verbose_name="Location description")),
                ("temperature", models.FloatField(verbose_name="Temperature [°C]")),
                ("humidity", models.FloatField(verbose_name="Humidity")),
                ("was_raining", models.BooleanField(verbose_name="Raining?")),
                ("was_sunny", models.BooleanField(verbose_name="Sunny?")),
                (
                    "weather_note",
                    models.TextField(blank=True, verbose_name="Weather note"),
                ),
                ("name", models.TextField(verbose_name="Scent name")),
                ("author", models.TextField(verbose_name="Author")),
                ("scent_desc", models.TextField(verbose_name="Scent description")),
                (
                    "sampling_params",
                    models.TextField(blank=True, verbose_name="Sampling parameters"),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=scents.models.Attachment.upload_to),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                (
                    "scent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="scents.scent",
                    ),
                ),
            ],
        ),
    ]
